#!/usr/bin/env python3
"""
Generate synthetic ECG-like 256-sample beats, preprocessed exactly the way
the training pipeline does (bandpass 0.5-40 Hz @ 360 Hz, then min/max
normalize to [-1, 1]), quantize to Q8.8, and emit a C header of test vectors.

These are NOT labelled MIT-BIH beats -- they exist to drive the C kernel and
the NumPy references over the same inputs so the two can be compared. Their
job is to be in the right numeric regime (normalized to [-1, 1], ECG-shaped),
not to be clinically meaningful.
"""

import numpy as np
from scipy.signal import butter, filtfilt

FS = 360
WINDOW = 256
PRE_RPEAK = 90


def bandpass(sig, fs=FS, lowcut=0.5, highcut=40.0):
    nyq = 0.5 * fs
    b, a = butter(4, [lowcut / nyq, highcut / nyq], btype="band")
    return filtfilt(b, a, sig)


def normalize_beat(beat):
    mn, mx = beat.min(), beat.max()
    if mx - mn < 1e-6:
        return beat
    return 2.0 * (beat - mn) / (mx - mn) - 1.0


def _gauss(t, center, width, amp):
    return amp * np.exp(-0.5 * ((t - center) / width) ** 2)


def synth_beat(rng, morphology="normal"):
    """Crude P-QRS-T construction with randomized morphology."""
    t = np.arange(WINDOW, dtype=np.float64)
    r = PRE_RPEAK

    if morphology == "normal":
        sig = (_gauss(t, r - 25, 6, rng.uniform(0.10, 0.18))       # P
               + _gauss(t, r - 5, 2.0, -rng.uniform(0.10, 0.20))    # Q
               + _gauss(t, r, 2.4, rng.uniform(0.9, 1.2))           # R
               + _gauss(t, r + 6, 3.0, -rng.uniform(0.15, 0.30))    # S
               + _gauss(t, r + 42, 12, rng.uniform(0.18, 0.32)))    # T
    elif morphology == "wide":       # VEB-like: wide, no P, discordant T
        sig = (_gauss(t, r - 2, 7.0, rng.uniform(0.7, 1.1))
               + _gauss(t, r + 12, 9.0, -rng.uniform(0.4, 0.8))
               + _gauss(t, r + 50, 16, -rng.uniform(0.2, 0.4)))
    elif morphology == "inverted":
        sig = (_gauss(t, r - 25, 6, -rng.uniform(0.08, 0.15))
               + _gauss(t, r, 2.6, -rng.uniform(0.8, 1.1))
               + _gauss(t, r + 40, 12, rng.uniform(0.15, 0.30)))
    else:                            # paced / noisy
        sig = (_gauss(t, r - 8, 1.0, rng.uniform(0.6, 1.0))         # spike
               + _gauss(t, r + 4, 8.0, rng.uniform(0.4, 0.7))
               + _gauss(t, r + 45, 14, rng.uniform(0.1, 0.3)))

    sig = sig + rng.normal(0, 0.015, WINDOW)                        # noise
    sig = sig + 0.05 * np.sin(2 * np.pi * 0.3 * t / FS)             # baseline wander

    # Filter over a padded copy so filtfilt edge effects mirror the real
    # pipeline (which filters the whole record, then slices the window).
    padded = np.concatenate([sig[::-1], sig, sig[::-1]])
    filtered = bandpass(padded)[WINDOW:2 * WINDOW]
    return normalize_beat(filtered)


def quantize_q88(x):
    q = np.round(np.asarray(x) * 256).astype(np.int64)
    return np.clip(q, -32768, 32767).astype(np.int32)


def main(n=40, seed=7, out="test_vectors_synth.h"):
    rng = np.random.default_rng(seed)
    morphs = ["normal", "wide", "inverted", "paced"]
    beats = [synth_beat(rng, morphs[i % len(morphs)]) for i in range(n)]
    Xq = np.stack([quantize_q88(b) for b in beats])

    np.save("test_inputs_q88.npy", Xq)

    with open(out, "w") as f:
        f.write("/* Auto-generated by make_vectors.py -- synthetic ECG-like beats,\n"
                " * preprocessed and Q8.8-quantized like the training pipeline. */\n")
        f.write("#ifndef TEST_VECTORS_SYNTH_H\n#define TEST_VECTORS_SYNTH_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define NUM_TESTS {n}\n\n")
        f.write("static const int16_t test_inputs[NUM_TESTS][256] = {\n")
        for row in Xq:
            f.write("    { " + ", ".join(str(int(v)) for v in row) + " },\n")
        f.write("};\n\n#endif\n")

    print(f"wrote {out} and test_inputs_q88.npy  ({n} vectors)")
    print(f"input range: [{Xq.min()}, {Xq.max()}]  (Q8.8; +-256 == +-1.0)")


if __name__ == "__main__":
    main()
