/* Auto-generated by convert_weights.py — do not edit by hand.
 * Multi-Scale SE 1D-CNN (TINY), Q8.8 fixed point (scale = 256), BN folded.
 * Conv weights are [out_ch][in_ch][k]; dense weights are [out_dim][in_dim].
 */
#ifndef ECG_WEIGHTS_H
#define ECG_WEIGHTS_H

#include <stdint.h>

#define Q_FRAC_BITS 8
#define Q_SCALE     256


/* ---- Branch 1 (kernel=3, 1 -> 8) ---- */
extern const int16_t w_b1[8][1][3];
extern const int16_t b_b1[8];

/* ---- Branch 2 (kernel=5, 1 -> 8) ---- */
extern const int16_t w_b2[8][1][5];
extern const int16_t b_b2[8];

/* ---- Branch 3 (kernel=7, 1 -> 8) ---- */
extern const int16_t w_b3[8][1][7];
extern const int16_t b_b3[8];

/* ---- SE block 1 (8 -> 4 -> 8) ---- */
extern const int16_t w_se1_fc1[4][8];
extern const int16_t b_se1_fc1[4];
extern const int16_t w_se1_fc2[8][4];
extern const int16_t b_se1_fc2[8];

/* ---- SE block 2 (8 -> 4 -> 8) ---- */
extern const int16_t w_se2_fc1[4][8];
extern const int16_t b_se2_fc1[4];
extern const int16_t w_se2_fc2[8][4];
extern const int16_t b_se2_fc2[8];

/* ---- SE block 3 (8 -> 4 -> 8) ---- */
extern const int16_t w_se3_fc1[4][8];
extern const int16_t b_se3_fc1[4];
extern const int16_t w_se3_fc2[8][4];
extern const int16_t b_se3_fc2[8];

/* ---- ResBlock 1 (8 -> 16, 1x1 shortcut) ---- */
extern const int16_t w_r1a[16][8][3];
extern const int16_t b_r1a[16];
extern const int16_t w_r1b[16][16][3];
extern const int16_t b_r1b[16];
extern const int16_t w_r1s[16][8][1];
extern const int16_t b_r1s[16];

/* ---- ResBlock 2 (16 -> 16, identity) ---- */
extern const int16_t w_r2a[16][16][3];
extern const int16_t b_r2a[16];
extern const int16_t w_r2b[16][16][3];
extern const int16_t b_r2b[16];

/* ---- Classifier ---- */
extern const int16_t w_fc1[16][16];
extern const int16_t b_fc1[16];
extern const int16_t w_fc2[5][16];
extern const int16_t b_fc2[5];

#endif /* ECG_WEIGHTS_H */
